spring.application.name=vatManager


spring.datasource.url=jdbc:sqlite:database.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA/Hibernate Configuration

#spring.jpa.database-platform=com.vatManager.vatManger.config.SQLiteDialect
#spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true