spring.application.name=vatManager


#This is static probably need to make it dynamic.
#spring.datasource.url=jdbc:sqlite:database.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:${DB_PATH}

# JPA/Hibernate Configuration

#spring.jpa.database-platform=com.vatManager.vatManger.config.SQLiteDialect
#spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Log to a file in user home
logging.file.name=${user.home}/TDS-ClientManager.log
logging.level.root=INFO